# Site settings
title: Sam Spilsbury
email: s@polysquare.org
url: https://smspillaz.github.io
description: "Confidence, Precision, Integrity. Open."
# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  secondary-dark: '#333333'
  tertiary-dark: '#999999'
  links: '#219ab3'

# Footer settings
footer: Sam Spilsbury

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: linkedin
    icon: linkedin
    url: https://www.linkedin.com/in/tsspilsbury
  - title: launchpad
    icon: ge
    url: http://launchpad.net/~smspillaz
  - title: github
    icon: github
    url: https://github.com/smspillaz

collections:
  projects:
    output: true
  artwork:
    output: true
  pages:
    output: true
  work:
    output: true
  volunteer:
    output: true
  interned:
    output: true

# Build settings
markdown: kramdown
permalink: pretty
