# Site settings
title: Sam Spilsbury
email: s@polysquare.org
url: https://smspillaz.github.io
description: "Confidence, Precision, Integrity. Open."
# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  secondary-dark: '#333333'
  tertiary-dark: '#999999'
  links: '#219ab3'

# Footer settings
footer: Sam Spilsbury

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: linkedin
    url: https://au.linkedin.com/in/sam-spilsbury-58031451
  - title: launchpad
    url: http://launchpad.net/~smspillaz
  - title: github
    url: https://github.com/smspillaz

collections:
  projects:
    output: true
  artwork:
    output: true
  pages:
    output: true
  work:
    output: true

# Build settings
markdown: kramdown
permalink: pretty
